### PR TITLE
Fix unicode

### PR DESCRIPTION
**Pull request by iamstarkov**
there is a problem with non latin titles, so i fixed it

### CODE REVIEW

**Comment by rstacruz** [comment]
Wow that's fast!

**Comment by rstacruz** [comment]
Oh. I think it needs to be kebabcase(unidecode(..)) instead of the other
way around. Sometimes unidecode will give you uppercase characters (
npmjs.com/unidecode has an example).

**Comment by rstacruz** [comment]
Fixed and released as 1.1.0, thanks for your help!

**Comment by iamstarkov** [comment]
happy to help

**Pull request merged**
